# Generated by Django 5.2.17 on 2026-09-14 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='License number must consist of 3 uppercase letters followed by 5 digits (e.g. ABC12345).', regex='^[A-Z]{3}\\d{5}$')]),
        ),
    ]
